# Generated by Django 2.2.9 on 2019-12-28 03:57

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_auto_20191227_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='category-1', editable=False, populate_from='name'),
            preserve_default=False,
        ),
    ]
